version = "0.5"
domain = "mediabrain.app"
site_name = "Mediabrain"
site_description = ""
fb_app_id = "561081350692034"
share_image_bucket_dir = "https://storage.googleapis.com/biblebot-image-share"
site_name_short = "MB"
under_construction = false
request_donations = false
request_donations_timeout = 15000  ; Time after page load to display PP Donate
;coords = "40.4883902,-85.6135714" ;Gas City
coords = "40.4211,-85.6538" ;Fairmount "nws_station_id = "KGUS", Grisom Air Force Base -  National Weather Service Station ID
nws_station_id = "KMZZ", ; Marion Municipal Airport - National Weather Service Station ID
